### ISSUE TITLE
Issue with baesian optimizer for custom dataset.

### ISSUE THREAD

**Issue by Rodrigo-A-Pereira** [Sujit-O/pykg2vec#175]
When using Bayesian Optimizer (BaysOptimizer) with a custom dataset I'm having problems with a "ValueError: Unknown dataset: [ds name]" error. 
According to the Traceback, the error is thrown from the "kgcontroller.py" module (**line 160**). The only hypothesis I had was that the custom dataset_path variable was Null, which I ended up confirming. 

This is the snippet i use for the calling the optimizer:
```
args = KGETuneArgParser().get_args(['-mn', model_name, '-ds', dataset_name, "-dsp", dataset_path])
bays_opt = BaysOptimizer(args=args)
bays_opt.optimize()
best = bays_opt.return_best()
```

I already verified both the dataset_name and dataset_path exist since i use them in the KG creation and it works just fine:
```
args = KGEArgParser().get_args(['-mn', model_name, '-ds', dataset_name, "-dsp", dataset_path])
knowledge_graph = KnowledgeGraph(dataset=args.dataset_name, custom_dataset_path=args.dataset_path)
```

After diving  bit into the code, it seemed to me that on the "bayesian_optimizer.py"
 module, the kge_args object passed to the config_obj is not given the path for the dataset (only the name) on **line 51**. Which seems that in consequence not passing it to its KnowlegeGraph object, raising the error.

**Note:** Adding this to the BaesianOptimizer init function seems to solve the issue for me.

**Full Traceback:**
```
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    main()
  File "train.py", line 72, in main
    bays_opt = BaysOptimizer(args=args)
  File "/usr/local/lib/python3.6/dist-packages/pykg2vec-0.0.51-py3.6.egg/pykg2vec/utils/bayesian_optimizer.py", line 51, in __init__
    self.config_local = self.config_obj(self.kge_args)
  File "/usr/local/lib/python3.6/dist-packages/pykg2vec-0.0.51-py3.6.egg/pykg2vec/config.py", line 65, in __init__
    self.knowledge_graph = KnowledgeGraph(dataset=args.dataset_name, custom_dataset_path=args.dataset_path)
  File "/usr/local/lib/python3.6/dist-packages/pykg2vec-0.0.51-py3.6.egg/pykg2vec/data/kgcontroller.py", line 160, in __init__
    raise ValueError("Unknown dataset: %s" % dataset)
ValueError: Unknown dataset: GOT
```

- OS: Windows 10

**Comment by Rodrigo-A-Pereira** [comment]
Thank you for the reply!
